# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-06 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.IntegerField()),
                ('powerType', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('pull_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RaceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.IntegerField()),
                ('side', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('pull_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
