# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-06 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_3v3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('realmId', models.IntegerField()),
                ('realmName', models.CharField(max_length=256)),
                ('realmSlug', models.CharField(max_length=256)),
                ('raceId', models.IntegerField()),
                ('classId', models.IntegerField()),
                ('specId', models.IntegerField()),
                ('factionId', models.IntegerField()),
                ('genderId', models.IntegerField()),
                ('seasonWins', models.IntegerField()),
                ('seasonLosses', models.IntegerField()),
                ('weeklyWins', models.IntegerField()),
                ('weeklyLosses', models.IntegerField()),
                ('pull_date', models.DateTimeField()),
            ],
        ),
    ]
