# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-06 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('arena_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            managers=[
                ('fresh', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='data_3v3',
            name='id',
        ),
        migrations.AddField(
            model_name='data_3v3',
            name='pulldatamodel_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arena_data.PullDataModel'),
            preserve_default=False,
        ),
    ]
