# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-07 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena_data', '0002_auto_20161006_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_3v3',
            name='pull_date',
        ),
        migrations.AddField(
            model_name='pulldatamodel',
            name='pull_date',
            field=models.DateTimeField(default="2001-01-01"),
            preserve_default=False,
        ),
    ]
