# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-07 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena_data', '0003_auto_20161007_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_3v3',
            name='dec_class',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='data_3v3',
            name='dec_race',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
