# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pepe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=32, unique=True)),
                ('url', models.CharField(max_length=512, unique=True)),
            ],
        ),
    ]
